course_planning/urls.py
"""
The url patterns for the course_planning application.
"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r"^$", views.ProgramListView.as_view(), name="courseplanning-program-list"),
    url(
        r"^teaching-preferences/$",
        login_required(views.TeachingProfileDetailView.as_view()),
        name="courseplanning-teaching-profile",
    ),
    url(
        r"^teaching-preferences/update/$",
        login_required(views.TeachingProfileWizardView.as_view()),
        name="courseplanning-teaching-profile-wizard",
    ),
    url(
        r"^(?P<slug>[\w-]+)/$",
        views.ProgramDetailView.as_view(),
        name="courseplanning-program-detail",
    ),
    url(
        r"^(?P<slug>[\w-]+)/graph.svg$",
        views.ProgramDetailSvgView.as_view(),
        name="courseplanning-program-graph",
    ),
]

course_planning/models.py
"""
Models for the course_planning application.
"""
#######################
from __future__ import print_function, unicode_literals

from autoslug import AutoSlugField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible

from . import conf
from .managers import CourseInfoManager, CourseProgramInfoManager, ProgramManager
from .utils import has_adjacent_timeslots

#######################################################################
#######################################################################
#######################################################################


class CoursePlanningBaseModel(models.Model):
    """
    An abstract base class.
    """

    active = models.BooleanField(default=True)
    created = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="creation time"
    )
    modified = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="last modification time"
    )

    class Meta:
        abstract = True


#######################################################################
#######################################################################
#######################################################################


@python_2_unicode_compatible
class Program(CoursePlanningBaseModel):
    """
    A Program of Study.  May be specific or general.
    """

    verbose_name = models.CharField(max_length=64)
    slug = AutoSlugField(max_length=64, unique=True, populate_from="verbose_name")
    ordering = models.PositiveSmallIntegerField(default=100)
    scheduled = models.BooleanField(
        default=False,
        verbose_name="Use for scheduling",
        help_text="Use courses in this program for scheduling",
    )
    public = models.BooleanField(
        default=False, help_text="Show in main list of programs"
    )
    description = models.TextField(
        blank=True, help_text=conf.get("program:description:help_text")
    )

    objects = ProgramManager()

    class Meta:
        ordering = ("ordering", "verbose_name")
        base_manager_name = "objects"

    def __str__(self):
        return self.verbose_name

    def get_absolute_url(self):
        return reverse("courseplanning-program-detail", kwargs={"slug": self.slug})


#######################################################################

#######################################################################


@python_2_unicode_compatible
class CourseInfo(CoursePlanningBaseModel):
    """
    A description of this model.
    """

    RUN_CHOICES = (
        ("a", "all years"),
        ("o", "odd years"),
        ("e", "even years"),
        ("i", "irregular"),
    )

    course = models.OneToOneField(
        "classes.Course", on_delete=models.CASCADE, limit_choices_to={"active": True}
    )
    has_lab = models.BooleanField(default=False)
    fall = models.BooleanField(default=False)
    winter = models.BooleanField(default=False)
    summer = models.BooleanField(default=False)
    runs = models.CharField(max_length=2, choices=RUN_CHOICES, default="a")

    objects = CourseInfoManager()

    class Meta:
        ordering = ("course",)
        verbose_name = "Course information"
        verbose_name_plural = "Course information"
        base_manager_name = "objects"

    def __str__(self):
        return str(self.course)

    # def get_absolute_url(self):
    #     return reverse('course_planning-course_planningmodel-detail', kwargs={'slug': self.slug})


#######################################################################


@python_2_unicode_compatible
class CourseProgramInfo(CoursePlanningBaseModel):
    """
    Information about this course in a particular program
    """

    CONSTRAINT_CHOICES = (("o", "Optional"), ("c", "Recommended"), ("r", "Required"))
    USUAL_YEAR_CHOICES = (
        ("0", "Not applicable"),
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("3.5", "3/4"),
        ("4", "4"),
        ("7", "Masters"),
        ("8", "PhD"),
    )

    course = models.ForeignKey(
        CourseInfo, on_delete=models.CASCADE, limit_choices_to={"active": True}
    )
    program = models.ForeignKey(
        Program, on_delete=models.CASCADE, limit_choices_to={"active": True}
    )
    usual_year = models.CharField(max_length=8, choices=USUAL_YEAR_CHOICES, default="0")
    constraint = models.CharField(max_length=2, choices=CONSTRAINT_CHOICES, default="o")

    objects = CourseProgramInfoManager()

    class Meta:
        ordering = ("usual_year", "course")
        unique_together = (("course", "program"),)
        verbose_name = "Course program information"
        verbose_name_plural = "Course program information"
        base_manager_name = "objects"

    def __str__(self):
        return str(self.course)

    # def get_absolute_url(self):
    #     return reverse('course_planning-course_planningmodel-detail', kwargs={'slug': self.slug})


#######################################################################


@python_2_unicode_compatible
class TeachingProfile(CoursePlanningBaseModel):

    person = models.OneToOneField(
        "people.Person",
        on_delete=models.CASCADE,
        limit_choices_to={"active": True},
        db_index=True,
    )
    agreed_load = models.PositiveSmallIntegerField(
        default=3, help_text="For the upcoming regular session only"
    )
    preference_same_day = models.BooleanField(
        default=False,
        help_text="Select this if you would prefer to have all of your teaching on the same day",
    )
    preference_no_back_to_back = models.BooleanField(
        default=False,
        help_text="Select this if you would prefer not to have any back to back teaching",
    )
    last_reviewed = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return "{}".format(self.person)

    class Meta:
        ordering = ("person",)

    def get_absolute_url(self):
        return reverse("courseplanning-teaching-profile")

    def get_semesterteachingpreferences(self):
        return self.semesterteachingpreference_set.filter(active=True)

    def get_favourite_coursepreferences(self, min_score=4):
        return (
            self.courseteachingpreference_set.filter(active=True)
            .exclude(score__lt=min_score)
            .order_by("-score", "course")
        )

    def get_favourite_timeslotpreferences(self, min_score=4):
        return (
            self.timeslotteachingpreference_set.filter(active=True)
            .exclude(score__lt=min_score)
            .order_by("-score", "timeslot")
        )

    def get_score(self, course_id, timeslot_id, jitter=0):
        """
        See also .schedule.utils.auto:_build_ranking_matrix(...)
        The score calculations should always align.
        """
        try:
            c_score = self.courseteachingpreference_set.get(course_id=course_id).score
        except CourseTeachingPreference.DoesNotExist:
            c_score = 0
        try:
            t_score = self.timeslotteachingpreference_set.get(
                timeslot_id=timeslot_id
            ).score
        except TimeslotTeachingPreference.DoesNotExist:
            t_score = 0
        score = c_score * (t_score * c_score + jitter)
        return score

    def get_remaining_loads(self, session):
        """
        Return the **remaining** loads as a pair:
        ``total_remaining, semester_remaining``
        """
        session_qs = self.draftsection_set.filter(active=True, session=session)
        total_load = self.agreed_load - session_qs.count()
        semesterprefs_qs = self.semesterteachingpreference_set.filter(active=True)
        term_data = {
            v["semester"]: v["preferred_load"]
            for v in semesterprefs_qs.values("semester", "preferred_load")
        }
        for code in term_data:
            term_data[code] -= session_qs.filter(semester=code).count()
        code_display = dict(SemesterTeachingPreference.SEMESTER_CHOICES)
        display = " / ".join(
            ["{}:{:.1f}".format(code_display[c][0], term_data[c]) for c in term_data]
        )
        term_data["display"] = display

        return total_load, term_data

    def has_back_to_back(self, session, semester_code):
        """
        Return ``True`` only when the preference is NOT for back to back
        teaching.
        """
        result = False
        if self.preference_no_back_to_back:
            from classes.models import Timeslot

            timeslot_id_list = (
                self.draftsection_set.filter(
                    active=True, session=session, semester=semester_code
                )
                .exclude(timeslot__isnull=True)
                .values_list("timeslot_id", flat=True)
            )
            online = Timeslot.objects.Online()
            timeslot_qs = Timeslot.objects.filter(pk__in=timeslot_id_list).exclude(
                pk=online.pk
            )
            if timeslot_qs.exists():
                result = has_adjacent_timeslots(timeslot_qs)
        return result

    def has_different_days(self, session, semester_code):
        """
        Return ``True`` only when the preference is for same day teaching.
        """
        result = False
        if self.preference_same_day:
            from classes.models import Timeslot

            timeslot_id_list = (
                self.draftsection_set.filter(
                    active=True, session=session, semester=semester_code
                )
                .exclude(timeslot__isnull=True)
                .values_list("timeslot_id", flat=True)
            )
            online = Timeslot.objects.Online()
            timeslot_qs = Timeslot.objects.filter(pk__in=timeslot_id_list).exclude(
                pk=online.pk
            )
            if timeslot_qs.exists():
                ref_day = timeslot_qs[0].day

course_planning/templates/course_planning/includes/app_breadcrumbs.html
{% url 'courseplanning-program-list' as app_top_url %}
{% if app_top_url %}
    {% if app_top_url != request.path %}
        <a href="{{ app_top_url }}">Programs</a>
    {% else %}
        Programs
    {% endif %}
{% endif %}

course_planning/templates/course_planning/includes/course_program_info.html
{# program.courseprograminfo_set.active #}

{% regroup program.courseprograminfo_set.active by get_usual_year_display as program_year_list %}

{% for year, course_program_info_list in program_year_list %}
    {% if year != "Not applicable" %}<h3>{% if year != "Masters" and year != "PhD" %}Year {% endif %}{{ year }} courses</h3>{% endif %}
    <table class="program-table">
        <thead>
            <tr>
                <th class="course-label" scope="col">Course</th>
                <th class="course-name" scope="col">Name</th>
                <th scope="col">Lab?</th>
                <th class="align-center" scope="colgroup" colspan="3">Terms</th>
            </tr>
        </thead>
        <tbody>
            {% for object in course_program_info_list %}
                {% with course=object.course %}
                    <tr class="constraint-{{ object.constraint }}"{% if object.constraint == "r" or object.constraint == "c" %} title="This course is {{ object.get_constraint_display|lower }}"{% endif %}>
                        <td class="course course-label">
                            <a href="{{ course.course.get_absolute_url }}">
                                {{ course.course.label_nbsp }}
                            </a>
                        </td>
                        <td class="course course-name">
                            {{ course.course.name }}
                        </td>
                            {% if course.has_lab %}
                                <td class="has-lab">L</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        </td>
                        {% if course.runs == 'i' %}
                            <td colspan="3">irregular</td>
                        {% else %}
                            {% if course.fall %}
                                <td class="runs-{% if course.runs != 'a' %}{{ course.runs|title }}{% endif %}F">{% if course.runs != 'a' %}{{ course.runs|title }}{% endif %}F</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                            {% if course.winter %}
                                <td class="runs-{% if course.runs != 'a' %}{{ course.runs|title }}{% endif %}W">{% if course.runs != 'a' %}{{ course.runs|title }}{% endif %}W</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                            {% if course.summer %}
                                <td class="runs-{% if course.runs != 'a' %}{{ course.runs|title }}{% endif %}S">{% if course.runs != 'a' %}{{ course.runs|title }}{% endif %}S</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        {% endif %}
                    </tr>
                {% endwith %}
            {% endfor %}
        </tbody>
    </table>
{% endfor %}

course_planning/templates/course_planning/includes/program_common.html
<p>
The regular schedule for our courses is also indicated in the tables below. F, W or S means that a course is taught in the Fall, Winter or Summer terms, respectively. L indicates that a lab is required.
</p>
For courses that are not taught every year, the prefix E indicates that the course is taught on even years (for example, an EW course runs Winter 2012, Winter 2014, etc.), O indicates odd years (for example, an OF course runs Fall 2013, Fall 2015, etc.).
</p>
<p>
Note that some regularly scheduled courses may sometimes not be offered.
</p>