course_planning/urls.py
"""
The url patterns for the course_planning application.
"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r"^$", views.ProgramListView.as_view(), name="courseplanning-program-list"),
    url(
        r"^teaching-preferences/$",
        login_required(views.TeachingProfileDetailView.as_view()),
        name="courseplanning-teaching-profile",
    ),
    url(
        r"^teaching-preferences/update/$",
        login_required(views.TeachingProfileWizardView.as_view()),
        name="courseplanning-teaching-profile-wizard",
    ),
    url(
        r"^(?P<slug>[\w-]+)/$",
        views.ProgramDetailView.as_view(),
        name="courseplanning-program-detail",
    ),
    url(
        r"^(?P<slug>[\w-]+)/graph.svg$",
        views.ProgramDetailSvgView.as_view(),
        name="courseplanning-program-graph",
    ),
]

course_planning/models.py
"""
Models for the course_planning application.
"""
#######################
from __future__ import print_function, unicode_literals

from autoslug import AutoSlugField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible

from . import conf
from .managers import CourseInfoManager, CourseProgramInfoManager, ProgramManager
from .utils import has_adjacent_timeslots

#######################################################################
#######################################################################
#######################################################################


class CoursePlanningBaseModel(models.Model):
    """
    An abstract base class.
    """

    active = models.BooleanField(default=True)
    created = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="creation time"
    )
    modified = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="last modification time"
    )

    class Meta:
        abstract = True


#######################################################################
#######################################################################
#######################################################################


@python_2_unicode_compatible
class Program(CoursePlanningBaseModel):
    """
    A Program of Study.  May be specific or general.
    """

    verbose_name = models.CharField(max_length=64)
    slug = AutoSlugField(max_length=64, unique=True, populate_from="verbose_name")
    ordering = models.PositiveSmallIntegerField(default=100)
    scheduled = models.BooleanField(
        default=False,
        verbose_name="Use for scheduling",
        help_text="Use courses in this program for scheduling",
    )
    public = models.BooleanField(
        default=False, help_text="Show in main list of programs"
    )
    description = models.TextField(
        blank=True, help_text=conf.get("program:description:help_text")
    )

    objects = ProgramManager()

    class Meta:
        ordering = ("ordering", "verbose_name")
        base_manager_name = "objects"

    def __str__(self):
        return self.verbose_name

    def get_absolute_url(self):
        return reverse("courseplanning-program-detail", kwargs={"slug": self.slug})


#######################################################################

#######################################################################


@python_2_unicode_compatible
class CourseInfo(CoursePlanningBaseModel):
    """
    A description of this model.
    """

    RUN_CHOICES = (
        ("a", "all years"),
        ("o", "odd years"),
        ("e", "even years"),
        ("i", "irregular"),
    )

    course = models.OneToOneField(
        "classes.Course", on_delete=models.CASCADE, limit_choices_to={"active": True}
    )
    has_lab = models.BooleanField(default=False)
    fall = models.BooleanField(default=False)
    winter = models.BooleanField(default=False)
    summer = models.BooleanField(default=False)
    runs = models.CharField(max_length=2, choices=RUN_CHOICES, default="a")

    objects = CourseInfoManager()

    class Meta:
        ordering = ("course",)
        verbose_name = "Course information"
        verbose_name_plural = "Course information"
        base_manager_name = "objects"

    def __str__(self):
        return str(self.course)

    # def get_absolute_url(self):
    #     return reverse('course_planning-course_planningmodel-detail', kwargs={'slug': self.slug})


#######################################################################


@python_2_unicode_compatible
class CourseProgramInfo(CoursePlanningBaseModel):
    """
    Information about this course in a particular program
    """

    CONSTRAINT_CHOICES = (("o", "Optional"), ("c", "Recommended"), ("r", "Required"))
    USUAL_YEAR_CHOICES = (
        ("0", "Not applicable"),
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("3.5", "3/4"),
        ("4", "4"),
        ("7", "Masters"),
        ("8", "PhD"),
    )

    course = models.ForeignKey(
        CourseInfo, on_delete=models.CASCADE, limit_choices_to={"active": True}
    )
    program = models.ForeignKey(
        Program, on_delete=models.CASCADE, limit_choices_to={"active": True}
    )
    usual_year = models.CharField(max_length=8, choices=USUAL_YEAR_CHOICES, default="0")
    constraint = models.CharField(max_length=2, choices=CONSTRAINT_CHOICES, default="o")

    objects = CourseProgramInfoManager()

    class Meta:
        ordering = ("usual_year", "course")
        unique_together = (("course", "program"),)
        verbose_name = "Course program information"
        verbose_name_plural = "Course program information"
        base_manager_name = "objects"

    def __str__(self):
        return str(self.course)

    # def get_absolute_url(self):
    #     return reverse('course_planning-course_planningmodel-detail', kwargs={'slug': self.slug})


#######################################################################


@python_2_unicode_compatible
class TeachingProfile(CoursePlanningBaseModel):

    person = models.OneToOneField(
        "people.Person",
        on_delete=models.CASCADE,
        limit_choices_to={"active": True},
        db_index=True,
    )
    agreed_load = models.PositiveSmallIntegerField(
        default=3, help_text="For the upcoming regular session only"
    )
    preference_same_day = models.BooleanField(
        default=False,
        help_text="Select this if you would prefer to have all of your teaching on the same day",
    )
    preference_no_back_to_back = models.BooleanField(
        default=False,
        help_text="Select this if you would prefer not to have any back to back teaching",
    )
    last_reviewed = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return "{}".format(self.person)

    class Meta:
        ordering = ("person",)

    def get_absolute_url(self):
        return reverse("courseplanning-teaching-profile")

    def get_semesterteachingpreferences(self):
        return self.semesterteachingpreference_set.filter(active=True)

    def get_favourite_coursepreferences(self, min_score=4):
        return (
            self.courseteachingpreference_set.filter(active=True)
            .exclude(score__lt=min_score)
            .order_by("-score", "course")
        )

    def get_favourite_timeslotpreferences(self, min_score=4):
        return (
            self.timeslotteachingpreference_set.filter(active=True)
            .exclude(score__lt=min_score)
            .order_by("-score", "timeslot")
        )

    def get_score(self, course_id, timeslot_id, jitter=0):
        """
        See also .schedule.utils.auto:_build_ranking_matrix(...)
        The score calculations should always align.
        """
        try:
            c_score = self.courseteachingpreference_set.get(course_id=course_id).score
        except CourseTeachingPreference.DoesNotExist:
            c_score = 0
        try:
            t_score = self.timeslotteachingpreference_set.get(
                timeslot_id=timeslot_id
            ).score
        except TimeslotTeachingPreference.DoesNotExist:
            t_score = 0
        score = c_score * (t_score * c_score + jitter)
        return score

    def get_remaining_loads(self, session):
        """
        Return the **remaining** loads as a pair:
        ``total_remaining, semester_remaining``
        """
        session_qs = self.draftsection_set.filter(active=True, session=session)
        total_load = self.agreed_load - session_qs.count()
        semesterprefs_qs = self.semesterteachingpreference_set.filter(active=True)
        term_data = {
            v["semester"]: v["preferred_load"]
            for v in semesterprefs_qs.values("semester", "preferred_load")
        }
        for code in term_data:
            term_data[code] -= session_qs.filter(semester=code).count()
        code_display = dict(SemesterTeachingPreference.SEMESTER_CHOICES)
        display = " / ".join(
            ["{}:{:.1f}".format(code_display[c][0], term_data[c]) for c in term_data]
        )
        term_data["display"] = display

        return total_load, term_data

    def has_back_to_back(self, session, semester_code):
        """
        Return ``True`` only when the preference is NOT for back to back
        teaching.
        """
        result = False
        if self.preference_no_back_to_back:
            from classes.models import Timeslot

            timeslot_id_list = (
                self.draftsection_set.filter(
                    active=True, session=session, semester=semester_code
                )
                .exclude(timeslot__isnull=True)
                .values_list("timeslot_id", flat=True)
            )
            online = Timeslot.objects.Online()
            timeslot_qs = Timeslot.objects.filter(pk__in=timeslot_id_list).exclude(
                pk=online.pk
            )
            if timeslot_qs.exists():
                result = has_adjacent_timeslots(timeslot_qs)
        return result

    def has_different_days(self, session, semester_code):
        """
        Return ``True`` only when the preference is for same day teaching.
        """
        result = False
        if self.preference_same_day:
            from classes.models import Timeslot

            timeslot_id_list = (
                self.draftsection_set.filter(
                    active=True, session=session, semester=semester_code
                )
                .exclude(timeslot__isnull=True)
                .values_list("timeslot_id", flat=True)
            )
            online = Timeslot.objects.Online()
            timeslot_qs = Timeslot.objects.filter(pk__in=timeslot_id_list).exclude(
                pk=online.pk
            )
            if timeslot_qs.exists():
                ref_day = timeslot_qs[0].day

course_planning/templates/course_planning/base.html
{% extends 'site_base.html' %}

{% block html_head %}
{{ block.super }}
{% block html_head_courseplanning_extra %}
{% endblock %}
{% endblock html_head %}


{% block page_title %}{% block head_subtitle %}Program information{% endblock %}{% endblock %}
{% block page_content_header %}{% block title %}Program information{% endblock %}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% block app_breadcrumbs %}
        <span class="divider">&gt;</span>
        {% include './includes/app_breadcrumbs.html' %}
        {% block page_breadcrumbs %}
        {% endblock %}
    {% endblock app_breadcrumbs %}
{% endblock breadcrumbs %}

{% block page_content_body %}
    <section>
        {% block courseplanning_content %}
            <p>
                MyApp Content.
            </p>
        {% endblock %}
    </section>
    {% block courseplanning_extra_content %}
    {% endblock %}
{% endblock page_content_body %}

course_planning/templates/course_planning/program_detail.html
{% extends 'course_planning/program_list.html' %}
{% load static markup %}

{# ########################################### #}

{% block html_head_courseplanning_extra %}
    <link type="text/css" rel="stylesheet" href="{% static 'course_planning/css/programs.css' %}">
{% endblock %}

{# ########################################### #}

{% block head_subtitle %}{{ object }} program{% endblock %}
{% block title %}{{ object }} program{% endblock %}

{# ########################################### #}

{% block page_breadcrumbs %}
    <span class="divider">&gt;</span>
    {{ object }}
{% endblock page_breadcrumbs %}

{# ########################################### #}

{% block courseplanning_content %}
    {% if program.description %}
        {{ program.description|restructuredtext }}
    {% else %}
        <p>
        Click on a course to see details as well as past midterm and final examinations.
        </p>
    {% endif %}
    {% include 'course_planning/includes/program_common.html' %}
    {% with course=program.courseprograminfo_set.active.0.course.course %}
        {% if course.prerequisite_set.active or course.reverse_prerequisites %}
            <ul class="pagenav">
                <li>
                    <a href="{% url 'courseplanning-program-graph' slug=program.slug %}">
                        Program graph
                    </a>
                </li>
            </ul>
        {% endif %}
    {% endwith %}
    {% if program.courseprograminfo_set.required.exists %}
        <p class="constraint-r">
            <span class="course">Required</span> courses appear <span class="course">like this</span>.
        </p>
    {% endif %}
    {% if program.courseprograminfo_set.recommended.exists %}
        <p class="constraint-c">
            <span class="course">Recommended</span> courses appear <span class="course">like this</span>.
        </p>
    {% endif %}
    {% if program.courseprograminfo_set.required.exists or program.courseprograminfo_set.recommended.exists %}
        {% if program.courseprograminfo_set.optional.exists %}
        <p class="constraint-o">
            <span class="course">Optional</span> courses appear <span class="course">like this</span>.
        </p>
        {% endif %}
    {% endif %}

    {% include 'course_planning/includes/course_program_info.html' %}
{% endblock %}

{# ########################################### #}

{% block courseplanning_extra_content %}
{% endblock %}

{# ########################################### #}

course_planning/templates/course_planning/program_list.html
{% extends 'course_planning/base.html' %}

{# ########################################### #}

{% block head_subtitle %}Program list{% endblock %}
{% block title %}Program list{% endblock %}

{# ########################################### #}

{% block courseplanning_content %}
    <ul>
        {% for object in object_list %}
            <li>
                <a href="{{ object.get_absolute_url }}">
                    {{ object }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

{# ########################################### #}

{% block courseplanning_extra_content %}
{% endblock %}

{# ########################################### #}

course_planning/templates/course_planning/teaching_profile_wizard.html
{% extends 'course_planning/teachingprofile_detail.html' %}

{# ########################################### #}

{% block head_subtitle %}Teaching preferences{% endblock %}
{% block title %}Teaching Preferences Update{% endblock %}

{# ########################################### #}

{% block html_head_courseplanning_extra %}
{{ block.super }}
{{ wizard.form.media }}
{% endblock %}

{# ########################################### #}
{% block courseplanning_content %}
    {% if form_title %}<h3>{{ form_title }}</h3>{% endif %}

    <p>
        <strong>Note:</strong>
        Indicated preferences are considered for teaching assignments
        but may not always be honoured.
    </p>


    <form enctype="multipart/form-data" action="" method="post" class="form">
        {% csrf_token %}
        <table class="table-form">
            {{ wizard.management_form }}
            {% if wizard.form.forms %}{# formset #}
                {{ wizard.form.management_form }}
                {% if wizard.form.non_form_errors %}
                    {{ wizard.form.non_form_errors }}
                {% endif %}
                {% for form in wizard.form.forms %}
                    {# custom formset templates #}
                    {% if formset_label %}
                        {% if formset_label == 'semester' %}
                            {% include './includes/formset/single_line_form.html' with form=form form_label=form.instance.get_semester_display %}
                        {% elif formset_label == 'course' %}
                            {% include './includes/formset/single_line_form.html' with form=form form_label=form.instance.course.label help_text=form.instance.course.name %}
                        {% elif formset_label == 'timeslot' %}
                            {% include './includes/formset/single_line_form.html' with form=form form_label=form.instance.timeslot.display %}
                        {% elif formset_label == 'question' %}
                            {% include './includes/formset/question_form.html' with form=form form_label=form.instance.question %}
                        {% else %}
                            {% include './includes/formset/single_line_form.html' with form=form form_label='UNKNOWN' %}
                        {% endif %}
                    {% else %}
                        {% include 'includes/form.html' %}
                    {% endif %}
                {% endfor %}
            {% else %}
                {% include 'includes/form.html' with form=wizard.form %}
            {% endif %}
            <tfoot>
            <tr class="visual-break form-row wizard-ctl">
                <td class="left">
                    {% if wizard.steps.prev %}
                    <button class="wizard-prev" name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">Start over</button>
                    {% endif %}
                </td>
                <td class="right">
                    <input class="wizard-next" type="submit" value="{% block form_button %}{% if wizard.steps.next %}Next{% else %}DONE{% endif %}{% endblock %}">
                </td>
            </tr>
            </tfoot>
        </table>
    </form>
{% endblock %}

{# ########################################### #}

{% block courseplanning_extra_content %}
    {% if formset_label == 'semester' %}
        <p class="instructions">
            Enter your preferred teaching load distribution
            for each term.
            You may use decimal points to indicate the relative
            strength of your preferences.
        </p>
        <p class="instructions example">
            <strong>Example 1:</strong>
            Fall 1.5; Winter 1.5 means you need to teach 3 courses,
            but you have no preference for which term the extra
            course occurs in.
        </p>
        <p class="instructions example">
            <strong>Example 2:</strong>
            Fall 1.25; Winter 1.75 means you need to teach 3 courses,
            but you have a stronger preference for the extra
            course in the winter term.
        </p>
        <p class="instructions example">
            <strong>Example 3:</strong>
            Fall 3; Winter 2 means you need to teach 5 courses,
            and your strong preference is for three in the fall
            and 2 in the winter.
        </p>
        <p class="instructions">
            <em>In all cases</em>
            your total must match the agreed load in the previous step.
        </p>
    {% elif formset_label == 'course' %}
        <p class="instructions">
            Indicate your teaching preference for the given courses on
            a scale of 0 to 9.

            <dl>
                <dt>0</dt>
                <dd>Indicates you are not qualified to teach the course.</dd>
                <dt>1&mdash;3</dt>
                <dd>Indicates you would prefer not to teach the course.</dd>
                <dt>4&mdash;6</dt>
                <dd>Indicates you are willing to teach the course, but it is not a preference.</dd>
                <dt>7&mdash;9</dt>
                <dd>Indicates a preferred course.</dd>
            </dl>
        </p>
    {% elif formset_label == 'timeslot' %}
        <p class="instructions">
            Indicate your teaching preference for the given timeslots on
            a scale of 0 to 9.

            <dl>
                <dt>0</dt>
                <dd>Indicates you are unable to teach at the specified time.</dd>
                <dt>1&mdash;3</dt>
                <dd>Indicates you would prefer not to teach in the given timeslot.</dd>
                <dt>4&mdash;6</dt>
                <dd>Indicates you are willing to teach at that time, but it is not a preference.</dd>
                <dt>7&mdash;9</dt>
                <dd>Indicates a preferred timeslot.</dd>
            </dl>
        </p>
    {% elif formset_label == 'question' %}
    {% endif %}
{% endblock %}

{# ########################################### #}

course_planning/templates/course_planning/teachingprofile_detail.html
{% extends 'course_planning/base.html' %}
{% load static %}

{# ########################################### #}


{% block head_subtitle %}Teaching preferences{% endblock %}
{% block title %}Teaching Preferences Summary{% endblock %}

{# ########################################### #}

{% block page_breadcrumbs %}
    <span class="divider">&gt;</span>
    Teaching preferences
{% endblock page_breadcrumbs %}

{# ########################################### #}

{% block courseplanning_content %}
    <ul class="pagenav">
        <li>
            <a href="{% url 'courseplanning-teaching-profile-wizard' %}">
                Review and update my teaching preferences
            </a>
        </li>
    </ul>

    <ul>
        <li>
            {% if object.last_reviewed %}
                You last reviewed your teaching preferences
                {{ object.last_reviewed|timesince }} ago.
            {% else %}
                You have <strong>never</strong> reviewed your teaching
                profile.  You should do this now.
            {% endif %}
        </li>

        <li>
            Agreed teaching load:
            <strong>
                {{object.agreed_load}}
            </strong>
            <ul>
                {% for p in object.get_semesterteachingpreferences %}
                    <li>
                        {{ p.get_semester_display }}:
                        <strong>
                            {{p.preferred_load}}
                        </strong>
                    </li>
                {% endfor %}
            </ul>
        </li>
        {% if object.preference_same_day %}
        <li>
            You prefer all of your teaching on the same days, when you
            teach more than one course.
        </li>
        {% endif %}
        <li>
            {% if object.preference_no_back_to_back %}
                You prefer no back to back classes.
            {% else %}
                You are okay with back to back classes.
            {% endif %}
        </li>
        <li>
            Preferred top 3 courses:
            <ul>
                {% for p in object.get_favourite_coursepreferences|slice:":3" %}
                    <li>
                        {{ p.course }}
                    </li>
                {% endfor %}
            </ul>
        </li>
        <li>
            Preferred top 3 timeslots:
            <ul>
                {% for p in object.get_favourite_timeslotpreferences|slice:":3" %}
                    <li>
                        {{ p.timeslot.display }}
                    </li>
                {% endfor %}
            </ul>
        </li>

    </ul>

{% endblock %}

{# ########################################### #}

{% block courseplanning_extra_content %}
{% endblock %}

{# ########################################### #}